CREATE SEQUENCE SEQ_T_CAMINHAO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_CAMINHAO (
    ID_CAMINHAO INTEGER DEFAULT SEQ_T_CAMINHAO.NEXTVAL NOT NULL,
    DS_REGISTRO VARCHAR2(100) NOT NULL,
    QT_CAPACIDADE NUMBER NOT NULL
);