CREATE SEQUENCE SEQ_T_IMOVEL
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_IMOVEL (
    ID_IMOVEL INTEGER DEFAULT SEQ_T_IMOVEL.NEXTVAL NOT NULL,
    NM_IMOVEL VARCHAR2(100) NOT NULL,
    DS_RUA VARCHAR2(100) NOT NULL,
    DS_BAIRRO VARCHAR2(100) NOT NULL,
    LX_RECICLAVEL NUMBER NOT NULL,
    LX_ORGANICO NUMBER NOT NULL
);