CREATE SEQUENCE SEQ_T_MORADOR
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_MORADOR (
    ID_MORADOR INTEGER DEFAULT SEQ_T_MORADOR.NEXTVAL NOT NULL,
    NM_MORADOR VARCHAR2(100) NOT NULL,
    NR_CPF VARCHAR2(100) NOT NULL,
    DS_EMAIL VARCHAR2(100) NOT NULL,
    IMOVEL_ID INTEGER NOT NULL
);