CREATE SEQUENCE SEQ_T_COLETA
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_COLETA (
    ID_COLETA INTEGER DEFAULT SEQ_T_COLETA.NEXTVAL NOT NULL,
    DT_COLETA DATE NOT NULL,
    TP_COLETA VARCHAR2(100) NOT NULL,
    CAMINHAO_ID INTEGER NOT NULL,
    IMOVEL_ID INTEGER NOT NULL
);