CREATE SEQUENCE SEQ_T_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE T_USUARIO (
    ID_USUARIO INTEGER DEFAULT SEQ_T_USUARIO.NEXTVAL NOT NULL,
    NM_USUARIO VARCHAR2(100) NOT NULL,
    DS_EMAIL VARCHAR2(100) NOT NULL,
    DS_SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER'
);